### ISSUE TITLE
i have taken this project as my mini project in my clg

### ISSUE THREAD

**Issue by saicharan507** [ArjunMnn/Drowsiness-Alert-System#1]
im gettng an issue 
please contact me to my mail or number 
mail id: charanvarma019@gmail.com
number : 9949253152

**Comment by saicharan507** [comment]
Traceback (most recent call last):
  File "c:\Users\chara\OneDrive\Desktop\new file driver\Drowsiness-Alert-System-master\drowsiness detection.py", line 68, in <module>
    lpred = model.predict_classes(l_eye)
AttributeError: 'Sequential' object has no attribute 'predict_classes'


**THIS WA THER ERROR**

**Comment by saicharan507** [comment]
Traceback (most recent call last):
  File "c:\Users\chara\OneDrive\Desktop\new file driver\Drowsiness-Alert-System-master\drowsiness detection.py", line 68, in <module>
    lpred = model.predict_classes(l_eye)
AttributeError: 'Sequential' object has no attribute 'predict_classes'

**THIS WAS THE ERROR BRO**

**Comment by PaVaNTrIpAtHi** [comment]
predict_x=model.predict(r_eye) 
rpred=np.argmax(predict_x,axis=1)
this will help you resolve issue
